### ISSUE TITLE
Difference to oa-core 

### ISSUE THREAD

**Issue by pwab** [vavrek/openassistant#16]
As far as I can see this repository seems to be the base of https://github.com/openassistant/oa-core. Are there any differences to the project data in the [openassistant organization](https://github.com/openassistant)?

I'm asking because I wanted to try Open Assistant and wanted to fork the current version.

**Comment by pwab** [comment]
I now just saw this sentence in the Readme:

> This is the first and original version of Open Assistant. The latest version can be found here: https://github.com/openassistant/oa-core/tree/next

Despite the fact that the link is down (404, no branch anymore) it answers my question.

**Comment by joshuashort** [comment]
@pwab there are lots of differences -- the referenced branch doesn't exist, but the project is somewhat alive. Reach out there if you want.
